name: Fetch Holidays

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'

jobs:
  fetch_holidays:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Fetch and save holidays
        run: |
          import json
          import os
          import requests
          from datetime import datetime

          current_year = datetime.now().year
          end_year = current_year + 10
          base_url = "https://feiertage-api.de/api/"

          os.makedirs("holidays", exist_ok=True)

          for year in range(2010, end_year + 1):
              response = requests.get(f"{base_url}?jahr={year}")
              if response.status_code == 200:
                  holidays = response.json()
                  with open(f"holidays/holidays_{year}.json", "w") as f:
                      json.dump(holidays, f, ensure_ascii=False, indent=4)
              else:
                  print(f"Error fetching holidays for the year {year}")
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@example.com"
          git add holidays/*.json
          git commit -m "Update holidays data"
          git push
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./holidays

